version: '3.9'
services:
  binduschool-test:
    image: postgres:latest
    container_name: test
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
